import { Habit } from '@/types/system';

export const INITIAL_HABITS: Habit[] = [
  {
    id: 'h_1',
    name: 'Hydrate & Electrolyte Flush',
    category: 'Nutrition',
    difficulty: 'E-Rank',
    priority: 'Medium',
    color: '#06b6d4',
    icon: 'Droplets',
    target: 3,
    targetUnit: 'Liters',
    frequency: 'Daily',
    reminderTime: '08:00',
    estimatedMinutes: 5,
    actualMinutes: 5,
    notes: 'Drink 1L immediately upon waking for optimal brain hydration.',
    checklist: [
      { id: 'c1', title: '1L Morning Water', completed: true },
      { id: 'c2', title: '1L Afternoon Water', completed: false },
      { id: 'c3', title: '1L Evening Water', completed: false }
    ],
    tags: ['Health', 'Energy', 'Daily'],
    customReward: '+5 XP Hydration Shield',
    streak: 5,
    longestStreak: 12,
    completedDates: ['2026-08-03', '2026-08-04', '2026-08-05', '2026-08-06'],
    archived: false,
    paused: false,
    xpValue: 5,
    createdAt: '2026-08-01'
  },
  {
    id: 'h_2',
    name: 'Shadow Conditioning Workout',
    category: 'Workout',
    difficulty: 'A-Rank',
    priority: 'Critical',
    color: '#ef4444',
    icon: 'Dumbbell',
    target: 1,
    targetUnit: 'Session',
    frequency: 'Daily',
    reminderTime: '17:00',
    estimatedMinutes: 60,
    actualMinutes: 60,
    notes: '100 Pushups, 100 Situps, 100 Squats, or Heavy Weight Training.',
    checklist: [
      { id: 'c1', title: 'Dynamic Warmup', completed: false },
      { id: 'c2', title: 'Main Lift Sets', completed: false },
      { id: 'c3', title: 'Core & Stretching', completed: false }
    ],
    tags: ['Fitness', 'Strength', 'Physical'],
    customReward: '+30 XP Strength Boost (+10 Physical Power)',
    customPunishment: '-15 XP Fatigue Penalty',
    streak: 4,
    longestStreak: 15,
    completedDates: ['2026-08-03', '2026-08-04', '2026-08-05', '2026-08-06'],
    archived: false,
    paused: false,
    xpValue: 30,
    createdAt: '2026-08-01'
  },
  {
    id: 'h_3',
    name: 'Deep Focus Study (2 Hours)',
    category: 'Study',
    difficulty: 'S-Rank',
    priority: 'Critical',
    color: '#a855f7',
    icon: 'BrainCircuit',
    target: 120,
    targetUnit: 'Minutes',
    frequency: 'Daily',
    reminderTime: '10:00',
    estimatedMinutes: 120,
    notes: 'Zero notification distraction. 2x 60-min Pomodoro Deep Work.',
    checklist: [
      { id: 'c1', title: 'Block 1 (60 mins)', completed: false },
      { id: 'c2', title: 'Block 2 (60 mins)', completed: false }
    ],
    tags: ['Knowledge', 'Focus', 'Career'],
    customReward: '+40 XP Intelligence Multiplier',
    customPunishment: '-20 XP Sloth Penalty',
    streak: 3,
    longestStreak: 8,
    completedDates: ['2026-08-04', '2026-08-05', '2026-08-06'],
    archived: false,
    paused: false,
    xpValue: 40,
    createdAt: '2026-08-01'
  },
  {
    id: 'h_4',
    name: 'Monarch Morning Awakening (5:30 AM)',
    category: 'Personal Development',
    difficulty: 'B-Rank',
    priority: 'High',
    color: '#eab308',
    icon: 'Sun',
    target: 1,
    targetUnit: 'Awakening',
    frequency: 'Daily',
    reminderTime: '05:30',
    estimatedMinutes: 1,
    notes: 'Out of bed instantly on first alarm. Zero snooze button.',
    tags: ['Discipline', 'Mindset'],
    customReward: '+20 XP Discipline Boost',
    streak: 6,
    longestStreak: 14,
    completedDates: ['2026-08-02', '2026-08-03', '2026-08-04', '2026-08-05', '2026-08-06'],
    archived: false,
    paused: false,
    xpValue: 20,
    createdAt: '2026-08-01'
  },
  {
    id: 'h_5',
    name: 'Mind Over Matter Meditation',
    category: 'Meditation',
    difficulty: 'D-Rank',
    priority: 'Medium',
    color: '#3b82f6',
    icon: 'Heart',
    target: 15,
    targetUnit: 'Minutes',
    frequency: 'Daily',
    reminderTime: '21:30',
    estimatedMinutes: 15,
    notes: 'Box breathing & mindfulness focus reset.',
    tags: ['Peace', 'Clarity', 'Health'],
    customReward: '+15 XP Vitality Restored',
    streak: 2,
    longestStreak: 10,
    completedDates: ['2026-08-05', '2026-08-06'],
    archived: false,
    paused: false,
    xpValue: 15,
    createdAt: '2026-08-01'
  },
  {
    id: 'h_6',
    name: 'Sovereign Reading (30 Pages)',
    category: 'Reading',
    difficulty: 'C-Rank',
    priority: 'High',
    color: '#10b981',
    icon: 'BookOpen',
    target: 30,
    targetUnit: 'Pages',
    frequency: 'Daily',
    reminderTime: '21:00',
    estimatedMinutes: 30,
    notes: 'Read non-fiction, strategy, or high-value literature.',
    tags: ['Books', 'Wisdom'],
    customReward: '+25 XP Knowledge Elixir',
    streak: 5,
    longestStreak: 21,
    completedDates: ['2026-08-03', '2026-08-04', '2026-08-05', '2026-08-06'],
    archived: false,
    paused: false,
    xpValue: 25,
    createdAt: '2026-08-01'
  },
  {
    id: 'h_7',
    name: 'Nightly System Reflection & Journal',
    category: 'Journaling',
    difficulty: 'E-Rank',
    priority: 'Medium',
    color: '#06b6d4',
    icon: 'PenTool',
    target: 1,
    targetUnit: 'Entry',
    frequency: 'Daily',
    reminderTime: '22:00',
    estimatedMinutes: 10,
    notes: 'Log wins, lessons learned, and tomorrow\'s quest plan.',
    tags: ['Review', 'Growth'],
    customReward: '+10 XP Insight Multiplier',
    streak: 4,
    longestStreak: 9,
    completedDates: ['2026-08-03', '2026-08-04', '2026-08-05', '2026-08-06'],
    archived: false,
    paused: false,
    xpValue: 10,
    createdAt: '2026-08-01'
  }
];
